resolver: lts-16.3
packages:
- "."
extra-deps:
  - socket-0.8.3.0
  - socket-unix-0.2.0.0
  - prometheus-metrics-ghc-1.0.1
  - wai-middleware-prometheus-1.0.0
  - git: https://github.com/lpeterse/haskell-mqtt.git
    commit: dd4eb856edd50439c6e73eda5878a5b6624e3eba
  - git: https://github.com/lpeterse/haskell-networking.git
    commit: b79d22a2b95c6ba4bb16b5b47bfb0ea06df9ddbd
flags: {}
extra-package-dbs: []
